# Component Info
info:
 component: SpringConfig-Server
 
# HTTP Server
server:
 port: 8888
 
spring:
 # Spring Cloud Config Server Repository
 cloud:
  config:
   server:
    git:
     uri: https://github.com/oliberegm/ConfiguracionCloud
 
 # Spring properties 
 profiles: 
  active: dev